services:
  web:
    container_name: todo_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - ${RAILS_PORT}:3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/tmp
      - /app/log
    env_file:
      - .env
    tty: true
    environment:
      RAILS_ENV: development

  db:
    container_name: todo_app_db
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  bundle_data: