# ベースイメージとして Ruby 3.2.4 を使用
FROM ruby:3.2.4

# ロケールとタイムゾーンの設定
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
ENV RAILS_ENV=development

# 必要なパッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev && \
    rm -rf /var/lib/apt/lists/*

# 作業ディレクトリを /app に設定
WORKDIR /app

# Gemfile と Gemfile.lock をコピーして、依存関係をインストール
COPY Gemfile Gemfile.lock /app/
RUN bundle install

# アプリケーションのコード全体をコピー
COPY . /app/

# エントリポイントスクリプトをコピー
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

# ポート 3000 をエクスポート
EXPOSE 3000

# Rails サーバーを起動
CMD ["rails", "server", "-b", "0.0.0.0"]